apiVersion: v1
kind: Service
metadata:
  name: kustomize-service
spec:
  selector:
    app: kustomize  # This should match the label in your Deployment
  ports:
    - protocol: TCP
      port: 80          # The port that the service exposes
      targetPort: 80     # The port on the container to which the traffic is routed
  type: ClusterIP        # This is the default type; you can change it to LoadBalancer or NodePort if needed
